version: '3.8'

services:
  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_DB: webproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webproject-network

volumes:
  postgres_data:

networks:
  webproject-network:
    driver: bridge 